# Generated by Django 5.0.7 on 2024-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('timings', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('child', 'child'), ('adult', 'adult'), ('aged person', 'aged person')], max_length=20)),
            ],
        ),
    ]
